---
###------------------------------------------------------
### CONFIGURE DEVICE WITH SPECIFIC COMMANDS IN SET FORMAT
###------------------------------------------------------
- name: Configure device with a specific commands in set mode
  hosts: juniper_routers
  connection: local
  gather_facts: no
  collections:
    - juniper.device
  
  tasks:

    - name: "====SEND CONFIGURATION TO A NETWORK DEVICE===="
      config: # CALL FOR A ANSIBLE MODULE

        # connection parameters
        user: "tomaszkot"
        passwd: "12wasko3"
        timeout: "240"

        # declare type of operation, command format and rollback timout
        load: merge
        format: 'set'
        #confirmed: 10
        confirm: 10
        check_commit_wait: 10
        # CLI comands to send
        lines:
          - 'set system host-name R1'
          - 'set system services netconf ssh'
          - 'set system time-zone Europe/Warsaw'
          - 'set system name-server 8.8.8.8'
          - 'set interfaces lo0.0 family inet address 1.1.1.1/32'
        
        dest_dir: '../output'
      
      # store the output in an object called "result"
      register: result

    - name: "====PRINT THE RESULT TO A CONSOLE===="
      # if there was any output from the change above thenprint the result to screen
      debug:
        var: result.diff_lines
      when: result.diff_lines is defined